dist: focal

language: go

go:
  - "1.13.x"

services:
  - docker

addons:
  apt:
    packages:
      - figlet

env:
  global:
    - TREE=birch
  jobs:
    - BIRD=eagle
    - BIRD=bluejay
    - BIRD=hummingbird

# install:

cache:
  apt: true

stages:
  - Tree Bird Tests

jobs:
  include:
    - stage: "Tree Bird Tests Additional"
      env:
        - TREE=pine
        - BIRD=helicopter

script: |
  make \
    BIRD=$BIRD \
    TREE=$TREE \
    test
