dist: focal

language: go

go:
  - "1.13.x"

services:
  - docker

addons:
  apt:
    packages:
      - figlet

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root

    - TREE=birch
  jobs:
    - BIRD=eagle
    - BIRD=bluejay
    - BIRD=hummingbird

install:
  - source .ci/setup_env.sh

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $DOWNLOAD_ROOT

before_cache:
  - DOWNLOAD_ONLY=1 source .ci/setup_env.sh

stages:
  - name: 'Tree Tests: $BIRD'

jobs:
  include:
    - stage: "Tree Bird Tests Additional"
      env:
        - TREE=pine
        - BIRD=helicopter

script: |
  make \
    BIRD=$BIRD \
    TREE=$TREE \
    test
